### ISSUE TITLE
bug: Uncaught (in promise) Error: "Badge" plugin is not implemented on android

### ISSUE THREAD

**Issue by ptmkenny** [robingenz/capacitor-badge#14]
**Describe the bug**

When trying to use this plugin on Android, I'm getting the following error

`Uncaught (in promise) Error: "Badge" plugin is not implemented on android
`

Test device: Galaxy A7 running Android 10
Testing method: `ionic build; ionic cap copy android`, then build in Android Studio 4.1.3 on Ubuntu via WSL and deploy directly to device
Plugin version: 1.0
Capacitor: 3.0.0-rc1 (also tried with rc0)
Ionic-native/core: 5.32.1

This is a React app working with a Drupal backend.

When I build my app for iOS and test on an iPhone X, the badges work as expected, so I know my code at least works some of the time.

**To Reproduce**

Here's code that causes the error, which is run when the user logs in:

```
export const badgeSetCount = async (count: number): Promise<void> => {
  console.log('making a call to badge', count);
  Badge.checkPermissions().then(
    async (permissionStatus) => {
      console.log('checking badge permissions', permissionStatus);
      if (permissionStatus.display === 'granted') {
        await Badge.set({ count });
      }
    },
  );
};
```

And here's code that causes the error when the user logs out:

```
export const badgeClear = async (): Promise<void> => {
  await Badge.clear();
};
```

**Expected behavior**
Badges are set with no error.

**Smartphone (please complete the following information):**

- Device: Galaxy A7
- OS: Android 10
- Browser Ionic React App

**Additional context**
I'm pretty new to app development so I might be missing something obvious.

When I updated to Capacitor 3, to make sure I did the upgrade correctly, I removed the old android project and created a new one from scratch (to ensure I didn't fail to make one of the small manual changes that would otherwise be required).

Other capacitor 3 plugins in the app (for example, storage) are working (the login cookie is set properly).  Also, I can upload a file with the Camera plugin.

**Comment by robingenz** [comment]
Thank you for the detailed description.

Please run `npx cap doctor` and paste the output here.

Make sure that `minifyEnabled` in `android/app/build.gradle` is set to `false`.

Sync the Android project:
```
npx cap sync android
```

Does the error occur on a debug or release build?

**Comment by ptmkenny** [comment]
```
 npx cap doctor
💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 2.4.7
  @capacitor/core: 2.4.7
  @capacitor/android: 2.4.7
  @capacitor/ios: 2.4.7

Installed Dependencies:

  @capacitor/cli: 3.0.0-rc.1
  @capacitor/core: 3.0.0-rc.1
  @capacitor/android: 3.0.0-rc.1
  @capacitor/ios: 3.0.0-rc.1

[error] Xcode is not installed

```

`minifyEnabled` is set to `false`.

`npx cap sync android`:

```
⠴ copy android [info] Found 1 Cordova plugin for android:
       cc.fovea.cordova.purchase@10.5.3
✔ copy android in 296.22ms
✔ Updating Android plugins in 26.88ms
[info] Found 8 Capacitor plugins for android:
       @capacitor/app@0.3.7
       @capacitor/camera@0.4.4
       @capacitor/haptics@0.3.7
       @capacitor/keyboard@0.6.0
       @capacitor/local-notifications@0.6.1
       @capacitor/network@0.4.7
       @capacitor/storage@0.3.7
       @robingenz/capacitor-badge@1.0.0
⠹ update android [info] Found 1 Cordova plugin for android:
       cc.fovea.cordova.purchase@10.5.3
✔ update android in 140.01ms
[info] Sync finished in 0.439s


```

Actually, upon further testing, running `npx cap sync android` appeared to fix it-- I am no longer getting the error `Badge plugin is not implemented`.

However, now the problem is that I don't see the badge on the icon, although there is no error.

The call to `Badget.set` seems OK:

```
<img width="785" alt="badge_set_debugging" src="https://user-images.githubusercontent.com/1451472/117478615-eb01b680-af4e-11eb-8397-138d0675ff0c.PNG">
```

**Comment by robingenz** [comment]
> On **Android** not all launchers support badges. This plugin uses [ShortcutBadger](https://github.com/leolin310148/ShortcutBadger). All supported launchers are listed [there](https://github.com/leolin310148/ShortcutBadger#supported-launchers).

Unfortunately, badges are not supported by all Android launchers.

I will close this issue as the error no longer appears.

**Comment by ptmkenny** [comment]
Thank you very much for the support.

I have managed to get the badges to display on Android, but only some of the time.  Even when the badge is displayed, it doesn't get updated correctly.  This is a launcher supported by ShortcutBadger.  However, this is really a separate problem from the original issue so if I can find exact steps to reproduce it (still debugging), I'll create a new issue later.

Again, thank you for developing this plugin; for my app, it's really helpful to have a badge count, and you made it possible.

**Comment by robingenz** [comment]
Glad the plugin helps you and thanks a lot!
Feel free to open a new issue. I will try to help. 
Of course, the problem should be reproducible.
