### ISSUE TITLE
feat: listen for notifications in the background and update badge count

### ISSUE THREAD

**Issue by skotturi** [robingenz/capacitor-badge#24]
**Is your feature request related to a problem? Please describe:**

The capacitor push notification plugin doesn't fire `pushNotificationReceived` when the app is in the background on iOS and thus I cannot increment the badge count using this plugin until the app is opened and then I can fetch `getDeliveredNotifications` which can be used to set the badge count.

**Describe the solution you'd like:**

A method that either listens for background notifications on iOS and exposes a listener or a method that listens for background notifications and directly increments the badge count.

**Describe alternatives you've considered:**

Firebase Messaging discussing this but I couldn't get it working:
https://firebase.google.com/docs/cloud-messaging/ios/first-message#register_for_remote_notifications

I've tried the following custom capacitor plugin:
RemoteNotification.swift:
```
import Foundation
import Capacitor

@objc(RemotePlugin)
public class RemotePlugin: CAPPlugin {

    public override func load() {
        NotificationCenter.default.addObserver(self, selector: #selector(self.handleDataMessage(notification:)), name: Notification.Name("OnRemoteMessage"), object: nil)
    }

    @objc func handleDataMessage( notification: NSNotification) {
        let userInfo: [AnyHashable : Any]
        userInfo = notification.object as! [AnyHashable : Any]
        print("Entire message \(userInfo)")
        self.notifyListeners("OnRemoteNotification", data: ["data":userInfo])
    }
}
```
RemoteNotification.m
```
#import <Capacitor/Capacitor.h>

CAP_PLUGIN(RemotePlugin, "RemotePlugin",
    CAP_PLUGIN_METHOD(handleDataMessage, CAPPluginReturnPromise);
)
```

Register the plugin with capacitor:
```
import { registerPlugin } from '@capacitor/core';

const RemotePlugin: any = registerPlugin('RemotePlugin');

export default RemotePlugin;
```

Use the plugin in the app:
```
import RemotePlugin from '../capacitor-plugins/remote-notifications';

RemotePlugin.addListener('OnRemoteNotification', (notification: object) => {
      console.log("ON REMOTE NOTIFICATION: "+notification);
      alert(notification);
      });
```

I'm happy to help but my knowledge of swift and of `UNUserNotificationCenter` is limited.

**Comment by skotturi** [comment]
Also tried turning on Background Mode support:
![image](https://user-images.githubusercontent.com/4960284/128297242-25469861-7168-46e1-a498-0dcfe5b6c421.png)

**Comment by robingenz** [comment]
Thank your for your feature request.
I was able to find the following comment on this topic: https://github.com/ionic-team/capacitor/issues/3736#issuecomment-717823916
So it seems that this is currently officially unsupported and not a bug.
Unfortunately, I do not know the reason for this.
From my point of view, it is not the task of this plugin to deal with incoming push notifications.
However, it should be possible in combination with a Push Notifications plugin.
I would still like to help you. 
Of course, it would be best if the Push Notifications plugin would handle this. I could not find any feature request for this so far. Maybe this would be a good approach.
As a temporary workaround, it should be possible to create a custom plugin. You have already tried this. 
Maybe we can find the reason why it does not work.

Check out this: [Pushing Background Updates to Your App](https://developer.apple.com/documentation/usernotifications/setting_up_a_remote_notification_server/pushing_background_updates_to_your_app)
Also, i use [this](https://capacitorjs.com/docs/ios/custom-code) as reference to add custom native iOS code.

Make sure that the remote notifications background mode is added (see [Enable the Remote Notifications Capability](https://developer.apple.com/documentation/usernotifications/setting_up_a_remote_notification_server/pushing_background_updates_to_your_app#2980038)).

Then u have to add [`didReceiveRemoteNotification`](https://developer.apple.com/documentation/uikit/uiapplicationdelegate/1623013-application) to your `AppDelegate`. From there you should be able to call your custom plugin code.
For this you can use the following plugin as reference: https://github.com/robingenz/capacitor-screen-orientation#ios

Please note that if a device receives a background notification, then the system may withhold and delay the delivery of the notification.

Make sure you test this on a real device (not simulator).

**Comment by robingenz** [comment]
I also just found this: https://github.com/ionic-team/capacitor-plugins/issues/200#issuecomment-633285481
Looks like someone else has had the same idea before and it seems to work.

**Comment by skotturi** [comment]
> I also just found this: [ionic-team/capacitor-plugins#200 (comment)](https://github.com/ionic-team/capacitor-plugins/issues/200#issuecomment-633285481)
> Looks like someone else has had the same idea before and it seems to work.

Thanks for all the ideas, I tried this but could not get it working. That solution was for capacitor v2, I'm not how much would need to change for v3, the syntax for handling notifications looks very different there than it does for the v3 capacitor push notification plugin and those both look different from the official FirebaseMessaging iOS SDK docs so I'm not sure exactly where to start.

**Comment by ptmkenny** [comment]
Did you see [this SO question/answer](https://stackoverflow.com/a/58543147/1209486)?  It seems the badge can be sent from the push notification itself, no plugin required.

**Comment by skotturi** [comment]
@ptmkenny that does help a lot actually, thank you. It doesn't allow you to increment, only set which means you have to keep track of the unread count in a firebase doc, read that doc before you send the notification then update the count from the frontend. Kind of annoying you cant just set `badge: ++` but it does update the badge count while the iOS app is in the background which is the ultimate goal.
