### ISSUE TITLE
Differences between autoClear and persist not clear

### ISSUE THREAD

**Issue by de-dan** [robingenz/capacitor-badge#50]
Hi @robingenz ! Fantastic job, like always.

Could you please update the readme to clarify the differences between `autoClear` and `persist`. It is a very similar configuration and it would be great to point out the major differences.

Sorry, maybe it is because of the flu not enough sleep, but it would be nice to have it clear and simple :)

Thanks again!
Best regards,
Daniel

**Comment by robingenz** [comment]
Thank you for your issue.

What exactly is confusing you or unclear?
It's relatively clear to me, but I also created the plugin, so it doesn't mean much. ^^ 

> `persist`: Configure whether the plugin should restore the counter after a reboot or app restart. Only available for Android and iOS.

If `persist` is set to `true`, the saved counter is restored when the app is started. The counter on the icon can be lost, for example, by a device reboot.

> `autoClear`: Configure whether the plugin should reset the counter after resuming the application. Only available for Android and iOS.

If `autoClear` is set to `true`, the counter is set to 0 every time the app is opened.

I admit that `persist` set to `true` and `autoClear` set to `true` is a meaningless combination.

**Comment by de-dan** [comment]
Hi @robingenz first of all, thank you for taking this seriously!

> I admit that `persist` set to `true` and `autoClear` set to `true` is a meaningless combination.

I think that's what was confusing to me. I think it is too late now to change the configuration to an enum based solution, since they are mutually exclusive? :D

Thanks again for the response. We can close this ticket, as it is clear to me. You have to decide which steps if any will follow up.

**Comment by robingenz** [comment]
> thank you for taking this seriously!

Of course!

>  I think it is too late now to change the configuration to an enum based solution, since they are mutually exclusive? :D

I could possibly do that with the Capacitor 5 update, but right now I don't want to publish a breaking change.

I'll wait and see if there are more questions about these options.
